# frozen_string_literal: true

require "fileutils"
require "rails/generators"
require "seams"
require "seams/generators/sibling_rubocop_writer"
require "seams/generators/host_injector"

module Seams
  module Generators
    # Removes an engine generated by `seams:engine`. Prompts for
    # confirmation unless --force is passed. Cleans up the surviving
    # engines' .rubocop.yml so OtherEngines no longer references the
    # engine that was just removed. Reverses host file edits made by
    # the canonical generators (mount line, includes) — leaves the
    # Gemfile alone since other engines may share gem deps.
    #
    # Run with: bin/rails generate seams:remove billing [--force]
    class RemoveGenerator < Rails::Generators::NamedBase
      include Seams::Generators::HostInjector

      class_option :force, type: :boolean, default: false,
                           desc: "Skip the confirmation prompt"

      # Maps engine name -> { mount: <Class>, includes: { user: [...], application_controller: [...] } }
      # Lets remove know what to undo for the canonical engines. Generic
      # engines aren't in this table and just get the directory deleted.
      CANONICAL_HOST_EDITS = {
        "auth" => {
          mount: "Auth::Engine",
          user_includes: %w[Auth::Authenticatable],
          application_controller_includes: %w[Auth::Authentication]
        },
        "notifications" => {
          mount: "Notifications::Engine",
          user_includes: %w[Notifications::Notifiable]
        },
        "billing" => {
          mount: "Billing::Engine",
          user_includes: %w[Billing::Billable]
        },
        "teams" => {
          mount: "Teams::Engine",
          user_includes: %w[Teams::Teamable]
        }
      }.freeze

      # Read the engine's create_table calls before its directory is
      # deleted. Used by write_drop_table_migration to generate the
      # reversal. Pattern-matches the literal ActiveRecord::Migration
      # call so we drop exactly what the engine created — never
      # host-side tables that happen to share the prefix.
      def capture_engine_tables
        engine_path = File.join(destination_root, "engines", name)
        return @engine_tables = [] unless File.directory?(engine_path)

        migrate_dir = File.join(engine_path, "db/migrate")
        return @engine_tables = [] unless File.directory?(migrate_dir)

        @engine_tables = Dir.glob(File.join(migrate_dir, "*.rb")).flat_map do |file|
          File.read(file).scan(/create_table\s+:(\w+)/).flatten
        end.uniq
      end

      def remove_engine_directory
        engine_path = File.join(destination_root, "engines", name)

        unless File.directory?(engine_path)
          @engine_was_present = false
          say "  skip    engines/#{name}/ (not found)", :yellow
          return
        end

        return unless options[:force] || confirm_removal?

        FileUtils.rm_rf(engine_path)
        @engine_was_present = true
        say "  remove  engines/#{name}/", :red
      end

      # Phase 1.7 — generate a drop-table migration in the host's
      # db/migrate so the host can run `bin/rails db:migrate` to
      # reclaim the engine's tables. Idempotent if-table-exists
      # check so re-running doesn't blow up on already-dropped tables.
      def write_drop_table_migration
        return unless @engine_was_present
        return if @engine_tables.nil? || @engine_tables.empty?

        migrate_dir = File.join(destination_root, "db/migrate")
        FileUtils.mkdir_p(migrate_dir)

        filename       = "#{drop_migration_timestamp}_drop_#{name}_tables.rb"
        migration_path = File.join(migrate_dir, filename)
        File.write(migration_path, drop_table_migration_body)

        say "  create  db/migrate/#{filename}", :green
        say "          → run `bin/rails db:migrate` to drop #{@engine_tables.size} table(s).", :yellow
      end

      # Phase 1.7 — re-run `bundle install` so the host's lockfile no
      # longer references the removed engine's gem deps (the canonical
      # generators each inject their own — bcrypt, faraday, etc; the
      # remover doesn't touch the Gemfile because deps are usually
      # shared, but a fresh `bundle install` keeps lockfile + Gemfile
      # in sync if the host did prune anything by hand). Skipped when
      # the engine was never present (no-op remove) or when there's
      # no Gemfile to bundle against.
      def run_bundle_install
        return unless @engine_was_present
        return unless File.exist?(File.join(destination_root, "Gemfile"))

        say "  run     bundle install (post-remove sync)", :green
        Dir.chdir(destination_root) do
          system("bundle", "install", "--quiet") || say("          → bundle install failed; resolve manually.", :red)
        end
      end

      def update_sibling_engines
        return unless @engine_was_present

        engines_root = File.join(destination_root, "engines")
        return unless Dir.exist?(engines_root)

        survivors = Dir.children(engines_root)
                       .select { |c| File.directory?(File.join(engines_root, c)) }
                       .reject { |c| c.start_with?(".") }
                       .sort

        return if survivors.empty?

        Seams::Generators::SiblingRubocopWriter.rewrite!(engines_root: engines_root, dirs: survivors)
        say "  update  .rubocop.yml of #{survivors.size} sibling engine(s)", :green
      end

      def unwire_from_host
        return unless @engine_was_present

        unwire_generic_host_edits
        unwire_canonical_host_edits(CANONICAL_HOST_EDITS[name])
      end

      private

      def unwire_generic_host_edits
        # Generic uninject — applies to every engine. The mount line +
        # initializer were created by the generic engine generator.
        host_uninject_mount(engine_class: "#{generic_module_name}::Engine")
        host_remove_initializer
      end

      def unwire_canonical_host_edits(edits)
        return unless edits

        host_uninject_mount(engine_class: edits[:mount]) if edits[:mount]
        Array(edits[:user_includes]).each do |concern|
          host_uninject_include("app/models/user.rb", concern)
        end
        Array(edits[:application_controller_includes]).each do |concern|
          host_uninject_include("app/controllers/application_controller.rb", concern)
        end
      end

      def confirm_removal?
        yes?("Remove engine `#{name}` and everything under engines/#{name}? [y/N]")
      end

      def generic_module_name
        name.split("_").map(&:capitalize).join
      end

      def host_remove_initializer
        path = File.join(destination_root, "config/initializers/#{name}.rb")
        return unless File.exist?(path)

        FileUtils.rm(path)
        say "  remove  config/initializers/#{name}.rb", :red
      end

      def drop_migration_timestamp
        Time.now.utc.strftime("%Y%m%d%H%M%S")
      end

      def drop_table_migration_body
        drops = @engine_tables.map do |table|
          %(    drop_table :#{table}, force: :cascade if table_exists?(:#{table}))
        end.join("\n")

        rails_version = Rails::VERSION::STRING.split(".")[0, 2].join(".") if defined?(Rails::VERSION::STRING)
        rails_version ||= "7.1"

        <<~RB
          # frozen_string_literal: true
          #
          # Drops every table created by the #{name} engine. Generated by
          # `bin/rails generate seams:remove #{name}`. Run with:
          #
          #   bin/rails db:migrate
          #
          # The if-table-exists guards make re-running safe.
          class Drop#{name.classify}Tables < ActiveRecord::Migration[#{rails_version}]
            def up
          #{drops}
            end

            def down
              raise ActiveRecord::IrreversibleMigration,
                    "Cannot recreate #{name} engine tables — re-run " \\
                    "`bin/rails generate seams:#{name}` to recreate the engine."
            end
          end
        RB
      end
    end
  end
end
