# frozen_string_literal: true

require "fileutils"
require "rails/generators"
require "seams"
require "seams/generators/sibling_rubocop_writer"
require "seams/generators/host_injector"

module Seams
  module Generators
    # Removes an engine generated by `seams:engine`. Prompts for
    # confirmation unless --force is passed. Cleans up the surviving
    # engines' .rubocop.yml so OtherEngines no longer references the
    # engine that was just removed. Reverses host file edits made by
    # the canonical generators (mount line, includes) — leaves the
    # Gemfile alone since other engines may share gem deps.
    #
    # Run with: bin/rails generate seams:remove billing [--force]
    class RemoveGenerator < Rails::Generators::NamedBase
      include Seams::Generators::HostInjector

      class_option :force, type: :boolean, default: false,
                           desc: "Skip the confirmation prompt"

      # Maps engine name -> { mount: <Class>, includes: { user: [...], application_controller: [...] } }
      # Lets remove know what to undo for the canonical engines. Generic
      # engines aren't in this table and just get the directory deleted.
      CANONICAL_HOST_EDITS = {
        "auth" => {
          mount: "Auth::Engine",
          user_includes: %w[Auth::Authenticatable],
          application_controller_includes: %w[Auth::Authentication]
        },
        "notifications" => {
          mount: "Notifications::Engine",
          user_includes: %w[Notifications::Notifiable]
        },
        "billing" => {
          mount: "Billing::Engine",
          user_includes: %w[Billing::Billable]
        },
        "teams" => {
          mount: "Teams::Engine",
          user_includes: %w[Teams::Teamable]
        }
      }.freeze

      def remove_engine_directory
        engine_path = File.join(destination_root, "engines", name)

        unless File.directory?(engine_path)
          @engine_was_present = false
          say "  skip    engines/#{name}/ (not found)", :yellow
          return
        end

        return unless options[:force] || confirm_removal?

        FileUtils.rm_rf(engine_path)
        @engine_was_present = true
        say "  remove  engines/#{name}/", :red
      end

      def update_sibling_engines
        return unless @engine_was_present

        engines_root = File.join(destination_root, "engines")
        return unless Dir.exist?(engines_root)

        survivors = Dir.children(engines_root)
                       .select { |c| File.directory?(File.join(engines_root, c)) }
                       .reject { |c| c.start_with?(".") }
                       .sort

        return if survivors.empty?

        Seams::Generators::SiblingRubocopWriter.rewrite!(engines_root: engines_root, dirs: survivors)
        say "  update  .rubocop.yml of #{survivors.size} sibling engine(s)", :green
      end

      def unwire_from_host
        return unless @engine_was_present

        edits = CANONICAL_HOST_EDITS[name]
        return unless edits

        host_uninject_mount(engine_class: edits[:mount]) if edits[:mount]
        Array(edits[:user_includes]).each do |concern|
          host_uninject_include("app/models/user.rb", concern)
        end
        Array(edits[:application_controller_includes]).each do |concern|
          host_uninject_include("app/controllers/application_controller.rb", concern)
        end
      end

      private

      def confirm_removal?
        yes?("Remove engine `#{name}` and everything under engines/#{name}? [y/N]")
      end
    end
  end
end
