# frozen_string_literal: true

require "fileutils"
require "rails/generators"
require "seams"
require "seams/generators/sibling_rubocop_writer"

module Seams
  module Generators
    # Removes an engine generated by `seams:engine`. Prompts for
    # confirmation unless --force is passed. Cleans up the surviving
    # engines' .rubocop.yml so OtherEngines no longer references the
    # engine that was just removed.
    #
    # Run with: bin/rails generate seams:remove billing [--force]
    class RemoveGenerator < Rails::Generators::NamedBase
      class_option :force, type: :boolean, default: false,
                           desc: "Skip the confirmation prompt"

      def remove_engine_directory
        engine_path = File.join(destination_root, "engines", name)

        unless File.directory?(engine_path)
          @engine_was_present = false
          say "  skip    engines/#{name}/ (not found)", :yellow
          return
        end

        return unless options[:force] || confirm_removal?

        FileUtils.rm_rf(engine_path)
        @engine_was_present = true
        say "  remove  engines/#{name}/", :red
      end

      def update_sibling_engines
        return unless @engine_was_present

        engines_root = File.join(destination_root, "engines")
        return unless Dir.exist?(engines_root)

        survivors = Dir.children(engines_root)
                       .select { |c| File.directory?(File.join(engines_root, c)) }
                       .reject { |c| c.start_with?(".") }
                       .sort

        return if survivors.empty?

        Seams::Generators::SiblingRubocopWriter.rewrite!(engines_root: engines_root, dirs: survivors)
        say "  update  .rubocop.yml of #{survivors.size} sibling engine(s)", :green
      end

      private

      def confirm_removal?
        yes?("Remove engine `#{name}` and everything under engines/#{name}? [y/N]")
      end
    end
  end
end
